CI & CD

diff --git a/.github/workflows/productServices.cicd.yml b/.github/workflows/productServices.cicd.yml
--- a/.github/workflows/productServices.cicd.yml
+++ b/.github/workflows/productServices.cicd.yml
@@ -82,11 +82,31 @@ jobs:
             port: 22
             script: |
               # Load the full user environment for non-interactive shells
-              source /home/ubuntu/.nvm/nvm.sh
-              source /home/ubuntu/.profile
+              if [ -f /home/ubuntu/.nvm/nvm.sh ]; then
+                source /home/ubuntu/.nvm/nvm.sh
+              else
+                echo "NVM not found. Skipping NVM setup."
+              fi
+
+              # Verify if `yarn` and `pm2` are available
+              if ! command -v yarn &> /dev/null; then
+                echo "Yarn not found. Installing Yarn."
+                npm install --global yarn
+              fi
+
+              if ! command -v pm2 &> /dev/null; then
+                echo "PM2 not found. Installing PM2."
+                npm install pm2 -g
+              fi
+              # source /home/ubuntu/.nvm/nvm.sh
+              # source /home/ubuntu/.profile
 
               cd /home/ubuntu/apps/build
+              echo install --production
               yarn install --production
+
+              # Check if PM2 process is running
+              
               # Assume PM2 is used, Replace with other command for other process manager
               # Assume you have script for run start in production and restart in production
               # Check if the PM2 process is running
