add setup.sh

diff --git a/.github/workflows/productServices.cicd.yml b/.github/workflows/productServices.cicd.yml
--- a/.github/workflows/productServices.cicd.yml
+++ b/.github/workflows/productServices.cicd.yml
@@ -93,6 +93,13 @@ jobs:
               fi
 
               # Verify if `yarn` and `pm2` are available
+              if ! command -v npm &> /dev/null; then
+                echo "npm not found. Installing Node.js."
+                curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
+                sudo apt-get install -y nodejs
+              fi
+
+              # Verify if `yarn` is available and install if missing
               if ! command -v yarn &> /dev/null; then
                 npm install -g yarn
               fi
@@ -101,8 +108,8 @@ jobs:
                 npm install -g pm2
               fi
 
-              # source /home/ubuntu/.nvm/nvm.sh
-              # source /home/ubuntu/.profile
+              source /home/ubuntu/.nvm/nvm.sh
+              source /home/ubuntu/.profile
 
               cd /home/ubuntu/apps/build
               echo "Installing dependencies..."
